name: test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
        arch:
          - amd64
          - "386"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go test -coverprofile="coverage.txt" -v ./...
        env:
          GOARCH: ${{ matrix.arch }}
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          flags: ${{ matrix.go }}
